language: java
install: true

jdk:
  - oraclejdk8

script:
  - mvn test -Dhost=$LOGISTICS_HOST -Dport=$LOGISTICS_PORT -DmgmtPort=$WILDFLY_MGMT_PORT -Dpassword=$WILDFLY_PASSWORD

cache:
  directories:
    - '$HOME/.m2/repository'
